package local.topdf;
import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.pdf.PdfRenderer;
import android.net.Uri;
import android.os.*;
import android.print.*;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.tom_roush.pdfbox.pdmodel.PDDocument;

public final class MainActivity extends Activity {
 TextView status;ImageView image;EditText first,last;Spinner layout;Button save,apply,print;File jobDir,original,converted,display,selected;String name="document";int count,displayPages,pageIndex,enginePid;volatile int serial;boolean busy,bound;
 final ExecutorService worker=Executors.newSingleThreadExecutor();final Handler handler=new Handler(Looper.getMainLooper());Messenger engine;final ArrayDeque<Uri> queue=new ArrayDeque<>();Bitmap bitmap;
 final Messenger response=new Messenger(new Handler(Looper.getMainLooper()){
  public void handleMessage(Message m){if(m.arg2!=serial)return;if(m.what==4){enginePid=m.arg1;return;}if(!busy)return;if(m.what==2){busy=false;handler.removeCallbacks(timeout);releaseEngine();final File ready=converted;final int generation=serial;worker.submit(()->{try{com.tom_roush.pdfbox.android.PDFBoxResourceLoader.init(MainActivity.this);final int pages;try(PDDocument d=PDDocument.load(ready)){pages=d.getNumberOfPages();}runOnUiThread(()->{if(generation!=serial)return;count=pages;display=ready;displayPages=count;first.setText("1");last.setText(Integer.toString(count));pageIndex=0;status.setText(name+" · "+count+"페이지");enable(true);renderPage();});}catch(Exception e){failure(e.getMessage());}});}else if(m.what==3)failure(m.getData().getString("error"));}
 });
 final Runnable timeout=()->{if(busy){cancel();status.setText("변환 시간 제한(180초)을 초과했습니다.");}};
 final ServiceConnection connection=new ServiceConnection(){public void onServiceConnected(ComponentName n,IBinder b){engine=new Messenger(b);Message m=Message.obtain(null,1);m.arg1=serial;Bundle data=new Bundle();data.putString("input",original.getPath());data.putString("output",converted.getPath());m.setData(data);m.replyTo=response;try{engine.send(m);}catch(RemoteException e){failure("엔진 연결 실패");}}
  public void onServiceDisconnected(ComponentName n){engine=null;if(busy)failure("변환 엔진이 종료되었습니다. 원본은 변경되지 않았습니다.");}};
 public void onCreate(Bundle state){super.onCreate(state);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(24,20,24,20);root.setBackgroundColor(Color.rgb(245,248,255));setContentView(root);
  TextView title=new TextView(this);title.setText("TopDF · 오프라인 PDF 변환");title.setTextSize(23);root.addView(title);status=new TextView(this);status.setText("Office·한글·PDF·이미지 · 인터넷 권한 없음");root.addView(status);
  LinearLayout top=new LinearLayout(this);root.addView(top);Button choose=button(top,"파일 선택",()->choose());Button cancel=button(top,"취소",()->cancel());button(top,"도움말",()->help());
  image=new ImageView(this);image.setBackgroundColor(Color.WHITE);image.setScaleType(ImageView.ScaleType.FIT_CENTER);root.addView(image,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout navigation=new LinearLayout(this);root.addView(navigation);button(navigation,"◀",()->{if(pageIndex>0){pageIndex--;renderPage();}});button(navigation,"▶",()->{if(pageIndex+1<displayCount()){pageIndex++;renderPage();}});
  layout=new Spinner(this);layout.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"원본 크기·방향","A4 세로","A4 가로"}));root.addView(layout);
  LinearLayout range=new LinearLayout(this);root.addView(range);TextView label=new TextView(this);label.setText("페이지 ");range.addView(label);first=new EditText(this);first.setInputType(2);first.setText("1");range.addView(first,new LinearLayout.LayoutParams(0,-2,1));TextView tilde=new TextView(this);tilde.setText(" ~ ");range.addView(tilde);last=new EditText(this);last.setInputType(2);last.setText("1");range.addView(last,new LinearLayout.LayoutParams(0,-2,1));apply=button(range,"미리보기",()->apply());
  LinearLayout footer=new LinearLayout(this);root.addView(footer);save=button(footer,"PDF 저장",()->save());print=button(footer,"인쇄창",()->print());enable(false);receive(getIntent());
 }
 Button button(LinearLayout row,String title,Runnable action){Button b=new Button(this);b.setText(title);b.setOnClickListener(v->action.run());row.addView(b,new LinearLayout.LayoutParams(0,-2,1));return b;}
 void enable(boolean ready){save.setEnabled(ready);print.setEnabled(ready);apply.setEnabled(ready);first.setEnabled(ready);last.setEnabled(ready);layout.setEnabled(ready);}
 void choose(){if(busy)return;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,10);}
 void receive(Intent i){if(Intent.ACTION_SEND_MULTIPLE.equals(i.getAction())){ArrayList<Uri> values=i.getParcelableArrayListExtra(Intent.EXTRA_STREAM);if(values!=null)queue.addAll(values);}else if(Intent.ACTION_SEND.equals(i.getAction())){Uri u=i.getParcelableExtra(Intent.EXTRA_STREAM);if(u!=null)queue.add(u);}else if(i.getData()!=null)queue.add(i.getData());if(!busy&&!queue.isEmpty())loadNext();}
 protected void onNewIntent(Intent i){super.onNewIntent(i);receive(i);}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;if(request==10){if(data.getClipData()!=null){for(int n=0;n<data.getClipData().getItemCount();n++)queue.add(data.getClipData().getItemAt(n).getUri());}else if(data.getData()!=null)queue.add(data.getData());loadNext();}else if(request==11&&data.getData()!=null){Uri target=data.getData();final File saving=selected;if(saving==null)return;worker.submit(()->{try(InputStream in=new FileInputStream(saving);OutputStream out=getContentResolver().openOutputStream(target,"wt")){if(out==null)throw new IOException("저장 위치를 열 수 없습니다.");byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1)out.write(b,0,n);runOnUiThread(()->{status.setText("PDF 저장 완료");if(!queue.isEmpty())loadNext();});}catch(Exception e){failure(e.getMessage());}});}}
 void loadNext(){if(busy||queue.isEmpty())return;cancel();Uri uri=queue.removeFirst();final int generation=serial;busy=true;enable(false);status.setText("파일을 불러오는 중…");worker.submit(()->{try{String fileName="document";try(Cursor c=getContentResolver().query(uri,null,null,null,null)){if(c!=null&&c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)fileName=c.getString(x);}}
   fileName=fileName.replaceAll("[/\\\\]","_");final String safe=fileName;final File loadingDir=new File(getCacheDir(),"job-"+UUID.randomUUID());if(!loadingDir.mkdirs())throw new IOException("임시 폴더 생성 실패");final File loadingOriginal=new File(loadingDir,safe),loadingConverted=new File(loadingDir,"converted.pdf");try(InputStream in=getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(loadingOriginal)){if(in==null)throw new IOException("파일을 열 수 없습니다.");byte[] b=new byte[65536];int n;long total=0;while((n=in.read(b))!=-1){if(generation!=serial){remove(loadingDir);throw new InterruptedIOException("취소했습니다.");}total+=n;if(total>512L*1024*1024)throw new IOException("512MB 이하의 파일을 선택하세요.");out.write(b,0,n);}}
   runOnUiThread(()->{if(generation!=serial){worker.submit(()->remove(loadingDir));return;}jobDir=loadingDir;original=loadingOriginal;converted=loadingConverted;name=safe;status.setText("기기 안에서 변환 중: "+safe);bound=bindService(new Intent(this,EngineService.class),connection,Context.BIND_AUTO_CREATE);if(!bound){failure("엔진 서비스 시작 실패");return;}handler.postDelayed(timeout,180000);});
  }catch(Exception e){if(generation==serial)failure(e.getMessage());}});}
 void releaseEngine(){if(bound){try{unbindService(connection);}catch(Exception ignored){}bound=false;}if(enginePid!=0){android.os.Process.killProcess(enginePid);enginePid=0;}engine=null;}
 void cancel(){serial++;busy=false;handler.removeCallbacks(timeout);releaseEngine();enable(false);display=null;converted=null;selected=null;if(bitmap!=null){image.setImageDrawable(null);bitmap.recycle();bitmap=null;}if(jobDir!=null){File old=jobDir;jobDir=null;worker.submit(()->remove(old));}status.setText("취소했습니다.");}
 void failure(String msg){runOnUiThread(()->{busy=false;handler.removeCallbacks(timeout);releaseEngine();status.setText("변환 실패");new AlertDialog.Builder(this).setMessage(msg==null?"변환에 실패했습니다.":msg).setPositiveButton("확인",null).show();});}
 static void remove(File f){File[] children=f.listFiles();if(children!=null)for(File c:children)remove(c);f.delete();}
 int displayCount(){return displayPages;}
 void renderPage(){if(display==null)return;File input=display;int index=pageIndex;worker.submit(()->{try(ParcelFileDescriptor fd=ParcelFileDescriptor.open(input,ParcelFileDescriptor.MODE_READ_ONLY);PdfRenderer renderer=new PdfRenderer(fd)){if(index>=renderer.getPageCount())return;try(PdfRenderer.Page p=renderer.openPage(index)){float scale=Math.min(2f,1600f/Math.max(p.getWidth(),p.getHeight()));Bitmap b=Bitmap.createBitmap(Math.max(1,(int)(p.getWidth()*scale)),Math.max(1,(int)(p.getHeight()*scale)),Bitmap.Config.ARGB_8888);b.eraseColor(Color.WHITE);p.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);runOnUiThread(()->{if(display!=input){b.recycle();return;}Bitmap old=bitmap;bitmap=b;image.setImageBitmap(b);if(old!=null)old.recycle();});}}catch(Exception e){failure(e.getMessage());}});}
 int[] options(){int a=Integer.parseInt(first.getText().toString()),b=Integer.parseInt(last.getText().toString());if(a<1||b<a||b>count)throw new IllegalArgumentException("페이지 범위를 확인하세요.");return new int[]{a,b,layout.getSelectedItemPosition()};}
 void apply(){if(converted==null||busy)return;try{int[] p=options();final int generation=serial;final File input=converted,out=new File(jobDir,"preview-"+UUID.randomUUID()+".pdf");busy=true;enable(false);worker.submit(()->{try{OfflineEngine.export(this,input,out,p[0],p[1],p[2]);runOnUiThread(()->{if(generation!=serial)return;busy=false;enable(true);display=out;displayPages=p[1]-p[0]+1;pageIndex=0;renderPage();});}catch(Exception e){if(generation==serial){failure(e.getMessage());runOnUiThread(()->enable(converted!=null));}}});}catch(Exception e){failure(e.getMessage());}}
 void makeSelected(Runnable action){if(busy)return;try{int[] p=options();final int generation=serial;final File input=converted,out=new File(jobDir,"selected-"+UUID.randomUUID()+".pdf");busy=true;enable(false);worker.submit(()->{try{OfflineEngine.export(this,input,out,p[0],p[1],p[2]);runOnUiThread(()->{if(generation!=serial)return;busy=false;enable(true);selected=out;action.run();});}catch(Exception e){if(generation==serial){failure(e.getMessage());runOnUiThread(()->enable(converted!=null));}}});}catch(Exception e){failure(e.getMessage());}}
 void save(){if(converted==null)return;makeSelected(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");int dot=name.lastIndexOf('.');i.putExtra(Intent.EXTRA_TITLE,(dot>0?name.substring(0,dot):name)+".pdf");startActivityForResult(i,11);});}
 void print(){if(converted==null)return;makeSelected(()->{final File file=selected;PrintManager manager=(PrintManager)getSystemService(PRINT_SERVICE);manager.print("TopDF PDF",new PrintDocumentAdapter(){
  public void onLayout(PrintAttributes old,PrintAttributes next,CancellationSignal signal,LayoutResultCallback cb,Bundle extras){if(signal.isCanceled()){cb.onLayoutCancelled();return;}try(PDDocument d=PDDocument.load(file)){cb.onLayoutFinished(new PrintDocumentInfo.Builder("TopDF.pdf").setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).setPageCount(d.getNumberOfPages()).build(),true);}catch(Exception e){cb.onLayoutFailed(e.getMessage());}}
  public void onWrite(PageRange[] ranges,ParcelFileDescriptor destination,CancellationSignal signal,WriteResultCallback cb){worker.submit(()->{try(PDDocument src=PDDocument.load(file);PDDocument out=new PDDocument();OutputStream stream=new FileOutputStream(destination.getFileDescriptor())){for(int n=0;n<src.getNumberOfPages();n++){if(signal.isCanceled()){cb.onWriteCancelled();return;}for(PageRange range:ranges)if(n>=range.getStart()&&n<=range.getEnd()){out.importPage(src.getPage(n));break;}}out.save(stream);cb.onWriteFinished(ranges);}catch(Exception e){cb.onWriteFailed(e.getMessage());}});}
 },null);});}
 void help(){new AlertDialog.Builder(this).setTitle("TopDF 오프라인 변환").setMessage("문서는 기기 안에서 변환됩니다. 인터넷 권한과 광고·분석 SDK가 없습니다.\n\n파일 앱의 공유 메뉴로 TopDF에 보내거나 파일 선택을 누르세요. 저장 시 Android 파일 선택기에서 원본 폴더 또는 원하는 폴더를 고르세요.\n\nHWP/HWPX 수식·차트·복잡한 서식은 원본과 차이가 날 수 있습니다. 글꼴과 문서 엔진 지원 범위에 따라 변환 결과가 달라집니다. 잠금 PDF는 먼저 잠금을 해제하세요.\n\nTopDF 코드 MIT. LibreOfficeKit Java 및 엔진 MPL-2.0, PDFBox Android Apache-2.0, 한글 엔진 및 의존성은 각 라이선스. 포함된 고지는 앱 자산 Licenses 폴더에 있습니다.").setNeutralButton("라이선스",(dialog,which)->licenses()).setPositiveButton("확인",null).show();}
 void licenses(){android.webkit.WebView view=new android.webkit.WebView(this);view.getSettings().setJavaScriptEnabled(false);view.getSettings().setAllowFileAccess(false);view.loadUrl("file:///android_asset/Licenses/android/THIRD_PARTY.html");new AlertDialog.Builder(this).setTitle("라이선스 · 출처").setView(view).setPositiveButton("닫기",(dialog,which)->view.destroy()).show();}
 protected void onDestroy(){cancel();worker.shutdown();super.onDestroy();}
}
