import plistlib, pathlib, uuid, sys
root=(pathlib.Path(sys.argv[1]) if len(sys.argv)>1 else pathlib.Path.home()/'Library/Services/PDF화.workflow')/'Contents'
root.mkdir(parents=True,exist_ok=True)
uid=str(uuid.uuid4()).upper()
action={'AMAccepts':{'Container':'List','Optional':True,'Types':['com.apple.cocoa.string']},'AMActionVersion':'2.0.3','AMApplication':['Automator'],'AMParameterProperties':{'COMMAND_STRING':{},'CheckedForUserDefaultShell':{},'inputMethod':{},'shell':{},'source':{}},'AMProvides':{'Container':'List','Types':['com.apple.cocoa.string']},'ActionBundlePath':'/System/Library/Automator/Run Shell Script.action','ActionName':'Run Shell Script','ActionParameters':{'COMMAND_STRING':'/usr/bin/open -a "$HOME/Applications/PDF로 변환.app" -- "$@"','CheckedForUserDefaultShell':True,'inputMethod':1,'shell':'/bin/zsh','source':''},'BundleIdentifier':'com.apple.RunShellScript','CFBundleVersion':'2.0.3','CanShowSelectedItemsWhenRun':False,'CanShowWhenRun':True,'Category':['AMCategoryUtilities'],'ClassName':'RunShellScriptAction','InputUUID':str(uuid.uuid4()).upper(),'Keywords':['Shell','Script'],'OutputUUID':str(uuid.uuid4()).upper(),'UUID':uid,'UnlocalizedApplications':['Automator'],'arguments':{'0':{'default value':0,'name':'inputMethod','required':False,'type':'0','uuid':'0'},'1':{'default value':'','name':'COMMAND_STRING','required':False,'type':'0','uuid':'1'},'2':{'default value':'/bin/zsh','name':'shell','required':False,'type':'0','uuid':'2'}},'isViewVisible':True,'nibPath':'/System/Library/Automator/Run Shell Script.action/Contents/Resources/Base.lproj/main.nib'}
workflow={'AMApplicationBuild':'521','AMApplicationVersion':'2.10','AMDocumentVersion':'2','actions':[{'action':action,'isViewVisible':True}],'connectors':[],'workflowMetaData':{'applicationBundleID':'com.apple.finder','applicationPath':'/System/Library/CoreServices/Finder.app','inputTypeIdentifier':'com.apple.Automator.fileSystemObject','outputTypeIdentifier':'com.apple.Automator.nothing','presentationMode':15,'processesInput':0,'serviceApplicationBundleID':'com.apple.finder','serviceApplicationPath':'/System/Library/CoreServices/Finder.app','serviceInputTypeIdentifier':'com.apple.Automator.fileSystemObject','serviceOutputTypeIdentifier':'com.apple.Automator.nothing','serviceProcessesInput':0,'systemImageName':'NSActionTemplate','useAutomaticInputType':False,'workflowTypeIdentifier':'com.apple.Automator.servicesMenu'}}
with (root/'document.wflow').open('wb') as f:plistlib.dump(workflow,f)
info={'CFBundleIdentifier':'local.topdf.quickaction','CFBundleName':'PDF화','NSServices':[{'NSMenuItem':{'default':'PDF화…'},'NSMessage':'runWorkflowAsService','NSRequiredContext':{'NSApplicationIdentifier':'com.apple.finder'},'NSSendFileTypes':['public.item'],'NSReturnTypes':[]}]}
with (root/'Info.plist').open('wb') as f:plistlib.dump(info,f)
print(root)
